import React from 'react';
import "./ContactSection.scss";

export const ContactSection = () => {
    return (
        <>
        
        <body class="bg-purple-200">
  <div class="container mx-auto p-4">
    <h1 class="text-center text-2xl font-bold mb-4 text-white">Planning Transmission MCR 2024</h1>
    <div class="overflow-x-auto">
    <table>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td>Férié</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>Repos</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>Déplacement OU Changement</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>Maladie</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td>Mois</td>
        <td>juillet </td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td>Semaine</td>
        <td>S27</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>S28</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>S29</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>S30</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>S31</td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td>Jour</td>
        <td>Lun</td>
        <td>Mar</td>
        <td>Mer</td>
        <td>Jeu</td>
        <td>Ven</td>
        <td>Sam</td>
        <td>Dim</td>
        <td>Lun</td>
        <td>Mar</td>
        <td>Mer</td>
        <td>Jeu</td>
        <td>Ven</td>
        <td>Sam</td>
        <td>Dim</td>
        <td>Lun</td>
        <td>Mar</td>
        <td>Mer</td>
        <td>Jeu</td>
        <td>Ven</td>
        <td>Sam</td>
        <td>Dim</td>
        <td>Lun</td>
        <td>Mar</td>
        <td>Mer</td>
        <td>Jeu</td>
        <td>Ven</td>
        <td>Sam</td>
        <td>Dim</td>
        <td>Lun</td>
        <td>Mar</td>
        <td>Mer</td>
    </tr>
    <tr>
        <td></td>
        <td>Binôme &amp; Date </td>
        <td>1</td>
        <td>2</td>
        <td>3</td>
        <td>4</td>
        <td>5</td>
        <td>6</td>
        <td>7</td>
        <td>8</td>
        <td>9</td>
        <td>10</td>
        <td>11</td>
        <td>12</td>
        <td>13</td>
        <td>14</td>
        <td>15</td>
        <td>16</td>
        <td>17</td>
        <td>18</td>
        <td>19</td>
        <td>20</td>
        <td>21</td>
        <td>22</td>
        <td>23</td>
        <td>24</td>
        <td>25</td>
        <td>26</td>
        <td>27</td>
        <td>28</td>
        <td>29</td>
        <td>30</td>
        <td>31</td>
    </tr>
    <tr>
        <td>A </td>
        <td>Abdellatif AARAB </td>
        <td>P2</td>
        <td>P1</td>
        <td>P1</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P1</td>
        <td>P1</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P1</td>
        <td>P1</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P1</td>
        <td>P1</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P1</td>
        <td>P1</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
    </tr>
    <tr>
        <td>B</td>
        <td>  karim idrissi </td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P1</td>
        <td>P1</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P1</td>
        <td>P1</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P1</td>
        <td>P1</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P1</td>
        <td>P1</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P1</td>
        <td>P1</td>
        <td>R</td>
        <td>R</td>
    </tr>
    <tr>
        <td>C</td>
        <td>Mohamed Mounkid </td>
        <td>P1</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P1</td>
        <td>P1</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P1</td>
        <td>P1</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P1</td>
        <td>P1</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P1</td>
        <td>P1</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P1</td>
        <td>P1</td>
    </tr>
    <tr>
        <td>Binôme A</td>
        <td> Aidi Sadeq </td>
        <td>P2</td>
        <td>P1</td>
        <td>P1</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P3</td>
        <td>P3</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P1</td>
        <td>P1</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P3</td>
        <td>P3</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P1</td>
        <td>P1</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
    </tr>
    <tr>
        <td></td>
        <td>El mehdi Samota</td>
        <td>P2</td>
        <td>P3</td>
        <td>P3</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P1</td>
        <td>P1</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P3</td>
        <td>P3</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P1</td>
        <td>P1</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P3</td>
        <td>P3</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
    </tr>
    <tr>
        <td>Binôme  B</td>
        <td>  Hakim Kazzouz</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P3</td>
        <td>P3</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P1</td>
        <td>P1</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P3</td>
        <td>P3</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P1</td>
        <td>P1</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P3</td>
        <td>P3</td>
        <td>R</td>
        <td>R</td>
    </tr>
    <tr>
        <td></td>
        <td>Mohcine Idsihammou</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P1</td>
        <td>P1</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P3</td>
        <td>P3</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P1</td>
        <td>P1</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P3</td>
        <td>P3</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P1</td>
        <td>P1</td>
        <td>R</td>
        <td>R</td>
    </tr>
    <tr>
        <td>Binôme  C</td>
        <td> Adil ZNIBER</td>
        <td>P3</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P1</td>
        <td>P1</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P3</td>
        <td>P3</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P1</td>
        <td>P1</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P1</td>
        <td>P1</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P3</td>
        <td>P3</td>
    </tr>
    <tr>
        <td></td>
        <td>Ilyas Ej-jebbouji</td>
        <td>P1</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P3</td>
        <td>P3</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P1</td>
        <td>P1</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P3</td>
        <td>P3</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P3</td>
        <td>P3</td>
        <td>R</td>
        <td>R</td>
        <td>P2</td>
        <td>P2</td>
        <td>P1</td>
        <td>P1</td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td>P1</td>
        <td>De 08H30 à 16H00</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td>P2</td>
        <td>De 15h30 à 23h30</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td>P3</td>
        <td>De 21h30 à 8h30</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
</table>
    </div>
    </div>
  </body>
        </>
    );
};

